import {Box} from "@mui/material";

export const metadata = {
    title: "create",
    description: "Generated by create next app",
};

export default async function Posts() {

    return (
        <>
            <Box>create forms</Box>
        </>
    )
}