import {Inter} from "next/font/google";
import AppBar from "@/components/AppBar";
import {AppRouterCacheProvider} from '@mui/material-nextjs/v13-appRouter';
import "./Globals.css"
import {Container} from "@mui/material";
import Box from "@mui/material/Box";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AppRouterCacheProvider>
            <Box className={"fixedContainer"}>
                <AppBar/>
                <Container sx={{minHeight: "100%", padding: "20px 0 30px 0"}}>
                    {children}
                </Container>
                <Footer/>
            </Box>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
