export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};
export default function Home() {
    return (
        <div>
            {0.2 + 0.1}
        </div>
    );
}
