import {Box, Typography} from "@mui/material";

export const metadata = {
    title: "about",
    description: "Generated by create next app",
};
export default function Page() {
    return (
        <Box>
            <Typography variant="h3" sx={{textAlign: "center", padding: "20px"}}>about page</Typography>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur debitis, dicta. Accusamus amet est
                excepturi facilis fugiat id impedit ipsum molestias neque placeat quae quis ratione reiciendis rem
                repudiandae ut vel. Ab ea excepturi explicabo impedit libero nobis nostrum reprehenderit voluptas. A
                adipisci alias aliquid at atque autem commodi cum cumque delectus dolor dolorem earum eius esse id
                inventore ipsa iure maxime minima molestiae, molestias nemo nihil non nostrum numquam officiis pariatur
                qui quibusdam quod similique ut velit, veritatis voluptatibus voluptatum. Adipisci, amet assumenda aut
                consectetur consequatur dolorem dolores doloribus dolorum earum eligendi error, expedita facilis fuga
                fugiat hic illum in incidunt ipsum, iure mollitia nihil nobis non numquam pariatur quaerat quibusdam
                ibu
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium r
                corporis cumque, debitis doloremque, ducimus enim ex facere facilis harum in itaque libero modi
                molestiae nam necessitatibus non officia omnis perferendis quae quis quisquam quos ratione rem repellat
                repudiandae rerum sequi totam voluptas voluptate. Animi aperiam consectetur cum cumque explicabo
                voluptatem! Accusamus aliquid amet aspernatur aut beatae dolore ea esse, est, id illo impedit inventore
                libero maiores modi neque nesciunt nisi odio possimus quibusdam soluta tempora temporibus voluptates?
                Aliquam amet aspernatur delectus eius laborum natus obcaecati. Culpa enim eos excepturi facere facilis,
                id ipsam laboriosam mollitia nemo non omnis sint sit suscipit ut, velit. Aspernatur, dolores et id
                laudantium nisi obcaecati quas? A accusamus adipisci amet animi blanditiis commodi cum deserunt
                exercitationem expedita explicabo ipsa iusto, laboriosam laborum placeat provident quae quia quisquam
                quod vel voluptatem? Atque cumque explicabo illo ipsa odit perferendis quam totam voluptatem? Aliquid
                amet cupiditate deserunt, distinctio excepturi id nesciunt similique veniam. Iste, quo, tempore. Atque
                commodi cumque debitis deserunt eius esse, facere inventore ipsum, nobis non nostrum odit officia porro
                quibusdam quod quos reprehenderit, sapiente tenetur voluptates voluptatibus. Aliquam, at autem
                consectetur consequuntur corporis dicta dolore dolorem enim est expedita explicabo facere impedit
                inventore ipsam laboriosam nemo nostrum placeat, quibusdam, rerum tenetur velit vitae voluptates. Ad
                aliquid explicabo harum, maiores rem repudiandae. Amet at dolore eius fugiat magnam odio perspiciatis
                quis quod tempore voluptatem? Aliquid asperiores commodi dignissimos dolores enim esse fugiat impedit
                itaque laborum natus odio quisquam sint sit tempora, vel? Accusantium ad aliquid aperiam autem corporis,
                doloremque eaque eligendi enim ipsam labore nam nobis, omnis perferendis, possimus praesentium repellat
                sed totam! Eos illum odio quaerat vero. Accusantium amet aperiam beatae culpa cum dignissimos dolores
                est eveniet exercitationem hic, illum incidunt, ipsum itaque iure labore libero nam odit provident
                dolorum
                illo optio unde voluptatum. Assumenda consequuntur debitis delectus dolor, et expedita explicabo hic
                modi molestiae neque nesciunt quam quod, repellat reprehenderit sapiente sint voluptas?</p>
        </Box>

    )
}