import { Inter } from "next/font/google";
import "./globals.css";
import classes from "./page.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={classes.container}>
        {children}
      </div>
      </body>
    </html>
  );
}
