import Link from "next/link";
import classes from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const getData = async () => {
  const response = await fetch("https://jsonplaceholder.typicode.com/posts")
  return response.json()
}
export default async function Home() {
  const posts = await getData()
  return (
    <main>{
      posts.map((i)=>{
        return <ul key={i.id}>
          <li>
            <Link href={`/${i.id}`}>{i.title}</Link>
          </li>
        </ul>
      })}</main>
  );
}
