import {Typography} from "@mui/material";

import React from "react";


export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function Layout({children}) {
    return (
        <>
            <Typography variant="h3" sx={{textAlign: "center", padding: "20px"}}>posts</Typography>
            {children}
        </>
    );
}
