
import React from "react";


export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function Layout({children}) {
    return (
        <>
            <text style={{textAlign: "center", padding: "20px"}}>posts</text>
            {children}
        </>
    );
}
